services:
    onchain-riddle:
        platform: linux/amd64
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VITE_CONTRACT_ADDRESS: ${VITE_CONTRACT_ADDRESS}
                VITE_RPC_URL: ${VITE_RPC_URL}
                PRIVATE_KEY: ${PRIVATE_KEY}
        ports:
            - "3564:3564"
        environment:
            - VITE_CONTRACT_ADDRESS=${VITE_CONTRACT_ADDRESS}
            - VITE_RPC_URL=${VITE_RPC_URL}
            - PRIVATE_KEY=${PRIVATE_KEY}
        restart: unless-stopped
        volumes:
            - ./logs:/var/log
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3564/"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
