version: "3.8"

services:
    onchain-riddle:
        platform: linux/amd64
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VITE_CONTRACT_ADDRESS: ${VITE_CONTRACT_ADDRESS}
                VITE_RPC_URL: ${VITE_RPC_URL}
        image: myzall/onchain-riddle:latest
        container_name: onchain-riddle
        ports:
            - "8080:3564"
        environment:
            - NODE_ENV=production
        restart: unless-stopped
